apiVersion: v1
kind: Pod
metadata:
  name: dw-client
  labels:
    app: dw-client
spec:
  containers:
  - name: dw-client
    image: remoandreoli/dw:latest
    imagePullPolicy: Always
    command: ["/bin/sh", "-c"]
    args: ['./src/dw_client_debug -sv dw-node -C 1000']
    ports:
    - containerPort: 7891
---
apiVersion: v1
kind: Service
metadata:
  name: dw-client
spec:
  selector:
    app: dw-client
  ports:
  - protocol: TCP
    port:  7891
    targetPort: 7891
