apiVersion: v1
kind: Pod
metadata:
  name: dw-client
  labels:
    app: dw-client
spec:
  containers:
  - name: dw-client
    image: remoandreoli/distwalk:latest
    imagePullPolicy: Always
    command: ["/bin/sh", "-c"]
    args: ['./dw_client --to dw-node -C 1000 -n 5']
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: dw-client
#spec:
#  selector:
#    app: dw-client
#  ports:
#  - protocol: TCP
#    port:  7891
#    targetPort: 7891
