apiVersion: v1
kind: Pod
metadata:
  name: dw-node-storage
  labels:
    app: dw-node-storage
spec:
  containers:
  - name: dw-node-storage
    image: remoandreoli/distwalk:latest
    imagePullPolicy: Always
    command: ["/bin/sh", "-c"]
    args: ['./dw_node -s ./data/data.data']
    volumeMounts:
    - name: storage
      mountPath: /distwalk/data
    ports:
    - containerPort: 7891
  volumes:
  - name: storage
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: dw-node-storage
spec:
  #clusterIP: None
  selector:
    app: dw-node-storage
  ports:
  - protocol: TCP
    port:  7891
    targetPort: 7891
