apiVersion: apps/v1
kind: Deployment
metadata:
  name: dw-node-deployment
  labels:
    apps: dw-node

spec:
  replicas: 1
  selector:
    matchLabels:
      app: dw-node
  template:
    metadata:
      labels:
        app: dw-node
    spec:
      containers:
      - name: dw-node
        image: remoandreoli/distwalk:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args: ['./dw_node -b 0.0.0.0']
        ports:
        - containerPort: 7891
---
apiVersion: v1
kind: Service
metadata:
  name: dw-node
spec:
  #clusterIP: None
  selector:
    app: dw-node
  ports:
  - protocol: TCP
    port:  7891
    targetPort: 7891
