apiVersion: v1
kind: Pod
metadata:
  name: pcroom17-dw-node
  labels:
    app: pcroom17-dw-node
spec:
  containers:
  - name: pcroom17-dw-node
    image: remoandreoli/distwalk:latest
    imagePullPolicy: Always
    command: ["/bin/sh", "-c"]
    args: ['./dw_node -b pcroom17-dw-node -s ./data/data.data']
    volumeMounts:
    - name: storage
      mountPath: /distwalk/data
    ports:
    - containerPort: 7891
  volumes:
  - name: storage
    emptyDir: {}
  nodeSelector:
    hostname: pcroom17
---
apiVersion: v1
kind: Service
metadata:
  name: pcroom17-dw-node
spec:
  #clusterIP: None
  type: NodePort
  selector:
    app: pcroom17-dw-node
  ports:
  - protocol: TCP
    port:  7891
    targetPort: 7891
    #nodePort: 37891
