- name: Common setup
  hosts: all
  become: yes
  tasks:
    - name: Install gcc-10
      apt:
        name: gcc-10
        state: present
    - name: Install gcc-10 alternative
      command: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10

    - name: Transfer DistWalk source files
      synchronize:
        src: ../src/
        dest: /tmp/dw_src/
        rsync_opts:
          - "--chmod=F755"
          - "--include='*.h'"
          - "--include='*.c'"
          - "--include='Makefile'"
          - "--exclude='*'" # exclude all other files

    - name: Compile DistWalk
      make:
        chdir: /tmp/dw_src/
        target: all

    - name: Ensure local DistWalk node service is stopped
      systemd:
        name: node.service
        enabled: no
        state: stopped
      register: node_service_stop
      failed_when:
        - node_service_stop.failed == true
        - '"Could not find the requested service" not in node_service_stop.msg'
    - name: Ensure local DistWalk client service is stopped
      systemd:
        name: client.service
        enabled: no
        state: stopped
      register: client_service_stop
      failed_when:
        - client_service_stop.failed == true
        - '"Could not find the requested service" not in client_service_stop.msg'
    - name: Kill previous process, if any
      shell: pkill -f "dw_node|dw_node_debug|dw_client|dw_client_debug" || true
      ignore_errors: true

- name: DistWalk node setup
  hosts: nodes
  become: yes
  tasks:
    - name: Run 
      shell: nohup /tmp/dw_src/dw_node -b {{ inventory_hostname }} -c 2-3 --sched-policy=dl:100000,1000000 &
    - name: Check if dw_node ready
      command: lsof -i :7891
      register: port_check
      retries: 10
      delay: 1
      until: port_check.rc == 0

