- name: Common DistWalk setup
  hosts: all
  become: yes
  tasks:
    - name: Install APT packages
      apt:
        name: 
          - gcc-10
          - cpufrequtils
        state: present
    - name: Install gcc-10 alternative
      command: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10

    - name: Transfer DistWalk source files from this localhost
      synchronize:
        src: ../src/
        dest: /tmp/dw_src/
        rsync_opts:
          - "--chmod=F755"
          - "--include='*.h'"
          - "--include='*.c'"
          - "--include='Makefile'"
          - "--exclude='*'" # exclude all other files
    
    - name: Transfer DistWalk auxiliary scripts from this localhost
      synchronize:
        src: ../script/
        dest: /tmp/dw_script/

    - name: Compile DistWalk
      make:
        chdir: /tmp/dw_src/
        target: all

    - name: Ensure DistWalk node's systemd service is stopped (if present)
      systemd:
        name: node.service
        enabled: no
        state: stopped
      register: node_service_stop
      failed_when:
        - node_service_stop.failed == true
        - '"Could not find the requested service" not in node_service_stop.msg'
    - name: Ensure DistWalk client's systemd service is stopped (if present)
      systemd:
        name: client.service
        enabled: no
        state: stopped
      register: client_service_stop
      failed_when:
        - client_service_stop.failed == true
        - '"Could not find the requested service" not in client_service_stop.msg'
    - name: Kill previous process, if any
      shell: pkill -f "dw_node|dw_node_debug|dw_node_tsan|dw_client|dw_client_debug|dw_client_tsan"
      register: pkill_result
      failed_when: pkill_result.rc > 1 

- name: DistWalk node setup (specify more parameters with --extra-vars "dw='<standard-dw-node-parameters>'" when running the playbook)
  hosts: nodes
  become: yes
  tasks:
    - name: Run DistWalk node
      shell: nohup /tmp/dw_src/dw_node -b {{ inventory_hostname }} {{ dw | default('') }} &
      register: node_out
    - name: DistWalk parameters (with extra variables)
      debug: 
        msg: "/tmp/dw_src/dw_node -b {{ inventory_hostname }} {{ dw | default('') }}"

    - name: Check if dw_node ready
      command: lsof -i :7891
      register: port_check
      retries: 10
      delay: 1
      until: port_check.rc == 0
