- import_playbook: dw-setup.yaml
- import_playbook: ic2e-setup.yaml
- import_playbook: host-setup.yaml

- name: Run DistWalk client
  hosts: clients
  tasks:
    - name: Run workload
      command: /tmp/dw_src/dw_client --to pcroom13 -C 2k -F pcroom14 -C 2k --skip 1,prob=0.75 -F pcroom15 -C 2k -r 10 -n 100
      register: out1

    - name: Print output to file
      copy:
        content: "{{out1.stdout}}"
        dest: /tmp/ic2e.log
      delegate_to: localhost

- import_playbook: host-teardown.yaml
- import_playbook: ic2e-teardown.yaml
