- hosts: all
  gather_facts: true
  tasks:
    - ping:
    - name: OS Release (Kernel Version)
      debug: 
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ansible_kernel }})"
